n$282=_fun___new(sizeof():) [line 1]
*&Bundle:=n$282 [line 2]
n$283=*&Bundle: [line 3]
n$284=_fun___new(sizeof():) [line 4]
_fun_AndroidDatabaseManager.<init>()(n$284:) [line 5]
*&AndroidDatabaseManager:=n$284 [line 6]
n$285=*&AndroidDatabaseManager: [line 7]
_fun_void AndroidDatabaseManager.onCreate(Bundle)(n$285:,n$283:) virtual [line 8]
_fun_void Activity.onResume()(n$285:) virtual [line 9]
_fun_void Activity.onPause()(n$285:) virtual [line 10]
_fun_void Activity.onStop()(n$285:) virtual [line 11]
_fun_void Activity.onDestroy()(n$285:) virtual [line 12]
n$286=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().com.dm.zbar.android.scanner.CameraPreview[line 53]: [line 13]
n$287=_fun___new(sizeof():) [line 14]
*&dummy_local7:=n$287 [line 15]
n$288=*&dummy_local7: [line 16]
_fun_void CameraPreview.surfaceDestroyed(SurfaceHolder)(n$286:,n$288:) virtual [line 17]
n$289=_fun___new(sizeof():) [line 18]
*&dummy_local8:=n$289 [line 19]
n$290=*&dummy_local8: [line 20]
n$291=_fun_Camera$Size CameraPreview.getOptimalPreviewSize(List,int,int)(n$286:,n$290:,0:,0:) virtual [line 21]
_fun_void CameraPreview.onLayout(boolean,int,int,int,int)(n$286:,0:,0:,0:,0:,0:) virtual [line 22]
_fun_void CameraPreview.showSurfaceView()(n$286:) virtual [line 23]
_fun_void CameraPreview.hideSurfaceView()(n$286:) virtual [line 24]
_fun_void CameraPreview.surfaceChanged(SurfaceHolder,int,int,int)(n$286:,n$288:,0:,0:,0:) virtual [line 25]
_fun_void CameraPreview.onMeasure(int,int)(n$286:,0:,0:) virtual [line 26]
n$292=_fun___new(sizeof():) [line 27]
*&Camera:=n$292 [line 28]
n$293=*&Camera: [line 29]
_fun_void CameraPreview.setCamera(Camera)(n$286:,n$293:) virtual [line 30]
_fun_void CameraPreview.surfaceCreated(SurfaceHolder)(n$286:,n$288:) virtual [line 31]
n$294=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.widget.AdapterView$OnItemSelectedListener[line 392]: [line 32]
n$295=_fun___new(sizeof():) [line 33]
*&View:=n$295 [line 34]
n$296=*&View: [line 35]
n$297=_fun___new(sizeof():) [line 36]
*&AdapterView:=n$297 [line 37]
n$298=*&AdapterView: [line 38]
_fun_void AndroidDatabaseManager$4$2.onItemSelected(AdapterView,View,int,long)(n$294:,n$298:,n$296:,0:,0:) virtual [line 39]
_fun_void AndroidDatabaseManager$4$2.onNothingSelected(AdapterView)(n$294:,n$298:) virtual [line 40]
n$299=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.view.View$OnClickListener[line 1222]: [line 41]
_fun_void AndroidDatabaseManager$9.onClick(View)(n$299:,n$296:) virtual [line 42]
n$300=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.view.View$OnClickListener[line 1170]: [line 43]
_fun_void AndroidDatabaseManager$8.onClick(View)(n$300:,n$296:) virtual [line 44]
n$301=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.view.View$OnClickListener[line 1143]: [line 45]
_fun_void AndroidDatabaseManager$7.onClick(View)(n$301:,n$296:) virtual [line 46]
n$302=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.widget.AdapterView$OnItemSelectedListener[line 300]: [line 47]
_fun_void AndroidDatabaseManager$4.onItemSelected(AdapterView,View,int,long)(n$302:,n$298:,n$296:,0:,0:) virtual [line 48]
_fun_void AndroidDatabaseManager$4.onNothingSelected(AdapterView)(n$302:,n$298:) virtual [line 49]
n$303=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.view.View$OnClickListener[line 194]: [line 50]
_fun_void AndroidDatabaseManager$2.onClick(View)(n$303:,n$296:) virtual [line 51]
n$304=*&#GB$de.tuhh.ti5.androidsvgnavimap.db.AndroidDatabaseManager.InferGeneratedHarness().android.view.View$OnClickListener[line 175]: [line 52]
_fun_void AndroidDatabaseManager$1.onClick(View)(n$304:,n$296:) virtual [line 53]
